// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgVpxgyZemQXCJ8AyUqROKePuEKSylaxo',
    appId: '1:1027134388053:web:5dd171140e5908be7fe1dc',
    messagingSenderId: '1027134388053',
    projectId: 'edwom-project',
    authDomain: 'edwom-project.firebaseapp.com',
    storageBucket: 'edwom-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0u0wUd4U-pcsTdIWbjDW8gYiBzeNXLCo',
    appId: '1:1027134388053:android:c1182d44d26628657fe1dc',
    messagingSenderId: '1027134388053',
    projectId: 'edwom-project',
    storageBucket: 'edwom-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPRAu2RuWykLEuG4z3_eUhnEvpoGk3E2I',
    appId: '1:1027134388053:ios:34d0cd3e5a9a54487fe1dc',
    messagingSenderId: '1027134388053',
    projectId: 'edwom-project',
    storageBucket: 'edwom-project.appspot.com',
    iosClientId: '1027134388053-23tlp15tu2pl9mjd2g0pahubahoa7hu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.edwom',
  );
}
